(define (saywhat)
  (setup-terminal)
  (initialize-keymaps)
  (display "Say what? ")
  (newline)
  (let ((line (process-line (make-line))))
    (newline)
    (display (line->string line))
    (newline)
    line))